{{- if .Values.secretEnv.data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mcp-mcpo-helm.fullname" . }}
  labels:
    {{- include "mcp-mcpo-helm.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.secretEnv.data }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}
{{- end }}
